### PR TITLE
Improvements to the WIP of #2 

### PR DESCRIPTION
**Pull request by jpt13653903**
Various corrections and tweaks relating to the WIP of #2

- Pulled in the new macros from "master"
- Checked that all line-endings are Unix-style
- Converted tabs to spaces
- Various typo corrections
- Various formatting improvements
- figure environment to \Figure
- Manual hypothesis to \Hypothesis
- Manual specification lists to SpecList environment
- Manual test table to TestTable environment
- Manual definition to \definition
- Hard-coded references to \label and \ref
- Quote character corrections
- Unicode ndash to "--"
- Changed "e.g." and "i.e." to use macros

### CODE REVIEW

**Comment by jpt13653903** [comment]
Hold on -- I'll solve the conflicts quickly...

**Comment by swinberg** [comment]
Really like the \todocard \notecard, super useful and I can imagine students using this to keep track of important things as well as supervisors using them for significant comments.

**Comment by jpt13653903** [comment]
> Really like the \todocard \notecard, super useful and I can imagine students using this...

Indeed -- I'm using it quite extensively for my thesis and finding it super handy :-)

**Comment by swinberg** [comment]
I'm done with the Design chapter, and plan to press on to the Experiment and Results chapters tomorrow if I find the time (perhaps once I've got that done you could have a look over the updates).

**Pull request merged**
